name: Pipeline de CI/CD do AlligaBot
# tudo nesse arquivo pode mudar ainda

on:
  push:
    # https://newbedev.com/github-actions-how-to-target-all-branches-except-master
    branches:
      - '**'
      - '*/*'
    paths:
      - 'actions/**'
      # esse path é temporário!!!
      - '.github/workflows/**'

jobs:
  build-actions-server-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .env file
        run: echo ${{ secrets.ENV }} > .env
      - name: Build da imagem do servidor de ações
        run: sudo docker-compose build
