name: Pipeline de CI/CD do AlligaBot
# tudo nesse arquivo pode mudar ainda

on:
  push:
    # https://newbedev.com/github-actions-how-to-target-all-branches-except-master
    branches:
      - '**'
      - '*/*'
    paths:
      - 'actions/**'
      # esse path é temporário!!!
      - '.github/workflows/**'

jobs:
  build-actions-server-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Criar arquivo .env 
        run: echo ${{ secrets.ENV }} > .env
      - name: Build da imagem do servidor de ações e subir container
        run: sudo docker-compose up actions -d --build
      - name: Executar linter (autopep8)
        run: make actions-lint
  
  # Seria bom usar cache no checkout
  build-bot-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Criar arquivo .env 
        run: echo ${{ secrets.ENV }} > .env
      - name: Build da imagem do bot e subir container
        run: sudo docker-compose up bot -d --build
      - name: Treinar bot
        run: make train
      - name: Testar bot (testes Rasa)
        run: make test

